# Generated by Django 5.1.4 on 2025-01-10 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_phone_remove_user_username_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2025, 1, 10, 17, 41, 24, 238161, tzinfo=datetime.timezone.utc)),
        ),
    ]
