# Generated by Django 5.1.4 on 2025-01-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('زن', 'F'), ('مرد', 'M')], max_length=3, null=True),
        ),
    ]
