# Generated by Django 5.1.4 on 2025-04-27 23:21

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_codemeli_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2025, 4, 28, 2, 51, 52, 313774), null=True),
        ),
    ]
