# Generated by Django 5.1.4 on 2025-04-28 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 28, 18, 55, 40, 623287, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
