# Generated by Django 5.1.4 on 2025-04-28 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 28, 19, 5, 38, 792549, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'زن'), ('M', 'مرد')], max_length=3, null=True),
        ),
    ]
