# Generated by Django 5.1.4 on 2025-04-28 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_birthdate_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 28, 20, 46, 47, 571972, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
