# Generated by Django 5.1.4 on 2025-01-07 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_accessory_access', to='home.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category_accessory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(blank=True, null=True, upload_to='Category'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='home.category'),
        ),
    ]
