# Generated by Django 5.1.4 on 2025-01-07 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_category_accessory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_accessory',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sub_category_accessory',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.category'),
        ),
    ]
