# Generated by Django 5.1.4 on 2025-01-07 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_category_parent_category_category_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_subcategories', to='home.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_brand',
            field=models.BooleanField(default=False),
        ),
    ]
