# Generated by Django 5.1.4 on 2025-01-07 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_category_category_brand_category_is_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_brand',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_brand',
        ),
    ]
