# Generated by Django 5.1.4 on 2025-01-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_color_size_product_status_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('None', 'هیج کدام'), ('Size', 'سایز'), ('Color', 'رنگ')], max_length=5, null=True),
        ),
    ]
