# Generated by Django 5.1.4 on 2025-04-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_comments_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderHomeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.ImageField(blank=True, null=True, upload_to='Slider')),
                ('slider_title', models.CharField(blank=True, max_length=300, null=True)),
                ('slider_text', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
