# Generated by Django 5.1.4 on 2025-04-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_productgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='name',
        ),
    ]
