# Generated by Django 5.1.4 on 2025-04-15 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_productgallery_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='save',
            field=models.ManyToManyField(blank=True, related_name='save_product_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
