# Generated by Django 5.1.4 on 2025-04-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_product_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_like',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
