# Generated by Django 5.1.4 on 2025-04-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_product_total_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
