# Generated by Django 5.1.4 on 2025-04-17 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_product_total_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_like',
        ),
    ]
