# Generated by Django 5.1.4 on 2025-04-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_product_total_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertising_video', models.FileField(blank=True, null=True, upload_to='videos')),
                ('advertising_title', models.CharField(max_length=100)),
            ],
        ),
    ]
