# Generated by Django 5.1.4 on 2025-04-18 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_advertisingvideo_advertising_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisingvideo',
            name='advertising_subtitle',
        ),
    ]
