# Generated by Django 5.1.4 on 2025-04-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_advertisingvideo_advertising_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisingvideo',
            name='advertising_text',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
