# Generated by Django 5.1.4 on 2025-04-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_advertisingvideo_advertising_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_fullName', models.CharField(max_length=120)),
                ('customer_phoneNumber', models.CharField(max_length=12)),
                ('is_called', models.CharField(blank=True, choices=[('CALLED', 'تماس گرفته شده'), ('NOT_CALLED', 'هنوز تماس گرفته نشده')], max_length=11, null=True)),
                ('needs_callback', models.CharField(blank=True, choices=[('NEEDED', 'نیاز به تماس مجدد'), ('NOT_NEEDED', 'عدم نیاز به تماس مجدد')], max_length=11, null=True)),
                ('customer_info', models.TextField()),
            ],
        ),
    ]
