# Generated by Django 5.1.4 on 2025-04-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_customercontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='customer_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
