# Generated by Django 5.1.4 on 2025-04-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_customercontact_customer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='is_called',
            field=models.CharField(blank=True, choices=[('CALLED', 'تماس گرفته شده'), ('NOT_CALLED', 'هنوز تماس گرفته نشده')], default='NOT_CALLED', max_length=11, null=True),
        ),
    ]
