# Generated by Django 5.1.4 on 2025-04-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_customercontact_is_called'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
