# Generated by Django 5.1.4 on 2025-04-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_product_unit_price_variants_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='save',
            new_name='saved_by_users',
        ),
    ]
