# Generated by Django 5.1.4 on 2025-04-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_rename_save_product_saved_by_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
