# Generated by Django 5.1.4 on 2025-04-27 23:06

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_comments_comment_like_alter_comments_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontact',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='update_time',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_time',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
