# Generated by Django 5.1.4 on 2025-04-27 23:21

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
